spring:
  profiles:
    active: local
---
spring:
  profiles: local
  application:
    name: ocp-10-demo1
  
#  datasource:
#    url: jdbc:postgresql://127.0.0.0:15432/sampledb
#    username: username
#    password: password
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-timeout: 20000
#      maximum-pool-size: 5
#  jpa: 
#    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        jdbc.lob.non_contextual_creation: true

hello: local-10

---
spring:
  profiles: ocp
  application:
    name: ocp-10-demo1

hello: ocp-10
